# Importing libraries

In [138]:
import pandas as pd
import pathlib
import numpy as np

In [115]:
pd.set_option("display.max_columns", None)

# Importing data

In [ ]:
# File paths
file_path_hhrv = "../Raw data/HHRV.txt"
file_path_perrv = "../Raw data/PERRV.txt"

In [68]:
# Column locations
col_specs_hhrv = [(0,4), (4,7), (7,9), (9,11), (11,12), (12,14), (14,16), (16,19), (19,21), (21,23), (23,24), (24,28), (28,33), (33,34), (34,35), (35,37), (37,39), (39,40), (40,41), (41,42), (42,44), (44,45), (45,46), (46,47), (47,55), (55,57), (57,65), (65,69), (69,72), (72,75), (75,85), (85,86)]
col_specs_perrv = [(0,4), (4,7), (7,9), (9,11), (11,12), (12,14), (14,16), (16,19), (19,21), (21,23), (23,24), (24,28), (28,33), (33,34), (34,35), (35,37), (37,39), (39,40), (40,41), (41,44), (44,45), (45,47), (47,49), (49,51), (51,53), (53,55), (55,57), (57,59), (59,64), (64,66), (66,68), (68,70), (70,75), (75,77), (77,79), (79,81), (81,83), (83,85), (85,90), (90,92), (92,94), (94,96), (96,101), (101,103), (103,105), (105,107), (107,109), (109,111), (111,116), (116,118), (118,120), (120,122), (122,127), (127,129), (129,131), (131,133), (133,135), (135,137), (137,142), (142,144), (144,146), (146,148), (148,153), (153,155), (155,157), (157,159), (159,161), (161,163), (163,168), (168,170), (170,172), (172,174), (174,179), (179,181), (181,183), (183,185), (185,187), (187,189), (189,194), (194,196), (196,198), (198,200), (200,205), (205,207), (207,209), (209,211), (211,213), (213,215), (215,220), (220,222), (222,224), (224,226), (226,231), (231,233), (233,235), (235,237), (237,239), (239,242), (242,250), (250,258), (258,261), (261,264), (264,274), (274,275)]

In [104]:
# Column names
col_names_hhrv = ['hhvar1', 'hhvar2', 'hhvar3', 'hhvar4', 'hhvar5', 'hhvar6', 'hhvar7', 'hhvar8', 'hhvar9', 'hhvar10', 'hhvar11', 'hhvar12', 'hhvar13', 'hhvar14', 'hhvar15', 'hhvar16', 'hhvar17', 'hhvar18', 'hhvar19', 'hhvar20', 'hhvar21', 'hhvar22', 'hhvar23', 'hhvar24', 'hhvar25', 'hhvar31', 'hhvar32', 'hhvar33', 'hhvar34', 'hhvar35', 'hhvar36', 'hhvar37']
col_names_perrv = ['pvar1', 'pvar2', 'pvar3', 'pvar4', 'pvar5', 'pvar6', 'pvar7', 'pvar8', 'pvar9', 'pvar10', 'pvar11', 'pvar12', 'pvar13', 'pvar14', 'pvar15', 'pvar16', 'pvar17', 'pvar19', 'pvar20', 'pvar21', 'pvar22', 'pvar23', 'pvar24', 'pvar25', 'pvar26', 'pvar61', 'pvar62', 'pvar63', 'pvar64', 'pvar65', 'pvar66', 'pvar67', 'pvar68', 'pvar69', 'pvar70', 'pvar71', 'pvar72', 'pvar73', 'pvar74', 'pvar75', 'pvar76', 'pvar77', 'pvar78', 'pvar79', 'pvar80', 'pvar81', 'pvar82', 'pvar83', 'pvar84', 'pvar85', 'pvar86', 'pvar87', 'pvar88', 'pvar89', 'pvar90', 'pvar91', 'pvar92', 'pvar93', 'pvar94', 'pvar95', 'pvar96', 'pvar97', 'pvar98', 'pvar99', 'pvar100', 'pvar101', 'pvar102', 'pvar103', 'pvar104', 'pvar105', 'pvar106', 'pvar107', 'pvar108', 'pvar109', 'pvar110', 'pvar111', 'pvar112', 'pvar113', 'pvar114', 'pvar115', 'pvar116', 'pvar117', 'pvar118', 'pvar119', 'pvar120', 'pvar121', 'pvar122', 'pvar123', 'pvar124', 'pvar125', 'pvar126', 'pvar127', 'pvar128', 'pvar129', 'pvar130', 'pvar131', 'pvar132', 'pvar133', 'pvar134', 'pvar135', 'pvar136', 'pvar137', 'pvar138', 'pvar139']

In [ ]:
# Loading HH and Person revisit files
df_hhrv = pd.read_fwf(filepath_or_buffer=file_path_hhrv, colspecs=col_specs_hhrv, names = col_names_hhrv, dtype = str)
df_perrv = pd.read_fwf(filepath_or_buffer=file_path_perrv, colspecs=col_specs_perrv, names = col_names_perrv, dtype = str)

In [116]:
df_hhrv.head()

,hhvar1,hhvar2,hhvar3,hhvar4,hhvar5,hhvar6,hhvar7,hhvar8,hhvar9,hhvar10,hhvar11,hhvar12,hhvar13,hhvar14,hhvar15,hhvar16,hhvar17,hhvar18,hhvar19,hhvar20,hhvar21,hhvar22,hhvar23,hhvar24,hhvar25,hhvar31,hhvar32,hhvar33,hhvar34,hhvar35,hhvar36,hhvar37,hhid
0,RVH7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,07,1,1,NaN,4,2,1,3,17100,01,09072023,10,3,6,1134607,4,Q1V22200011101
1,RVH7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,02,07,1,1,NaN,4,2,1,9,16475,01,09072023,11,3,6,1134607,4,Q1V22200011102
2,RVH7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,2,01,07,1,1,NaN,2,2,1,3,7980,01,09072023,12,3,6,1601799,4,Q1V22200011201
3,RVH7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,2,02,07,1,1,NaN,4,2,1,9,9517,01,09072023,14,3,6,1601799,4,Q1V22200011202
4,RVH7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,3,01,07,1,1,NaN,1,9,1,3,6833,01,09072023,10,3,6,1735282,4,Q1V22200011301

In [117]:
df_perrv.head()

,pvar1,pvar2,pvar3,pvar4,pvar5,pvar6,pvar7,pvar8,pvar9,pvar10,pvar11,pvar12,pvar13,pvar14,pvar15,pvar16,pvar17,pvar19,pvar20,pvar21,pvar22,pvar23,pvar24,pvar25,pvar26,pvar61,pvar62,pvar63,pvar64,pvar65,pvar66,pvar67,pvar68,pvar69,pvar70,pvar71,pvar72,pvar73,pvar74,pvar75,pvar76,pvar77,pvar78,pvar79,pvar80,pvar81,pvar82,pvar83,pvar84,pvar85,pvar86,pvar87,pvar88,pvar89,pvar90,pvar91,pvar92,pvar93,pvar94,pvar95,pvar96,pvar97,pvar98,pvar99,pvar100,pvar101,pvar102,pvar103,pvar104,pvar105,pvar106,pvar107,pvar108,pvar109,pvar110,pvar111,pvar112,pvar113,pvar114,pvar115,pvar116,pvar117,pvar118,pvar119,pvar120,pvar121,pvar122,pvar123,pvar124,pvar125,pvar126,pvar127,pvar128,pvar129,pvar130,pvar131,pvar132,pvar133,pvar134,pvar135,pvar136,pvar137,pvar138,pvar139,hhid,perid
0,RVP7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,01,1,1,45,2,08,01,10,NaN,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,721,20000,0,3,6,1134607,4,Q1V22200011101,Q1V2220001110101
1,RVP7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,02,2,2,41,2,08,01,10,NaN,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,NaN,0,0,3,6,1134607,4,Q1V22200011101,Q1V2220001110102
2,RVP7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,03,5,1,18,1,10,01,12,29,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,NaN,0,0,3,6,1134607,4,Q1V22200011101,Q1V2220001110103
3,RVP7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,04,5,2,16,1,08,01,10,27,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,NaN,0,0,3,6,1134607,4,Q1V22200011101,Q1V2220001110104
4,RVP7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,02,01,1,1,44,2,13,06,17,NaN,31,85,8,0,NaN,NaN,0,0,8,0,31,85,8,0,NaN,NaN,0,0,8,0,31,85,8,0,NaN,NaN,0,0,8,0,31,85,8,0,NaN,NaN,0,0,8,0,31,85,8,0,NaN,NaN,0,0,8,0,31,85,8,0,NaN,NaN,0,0,8,0,72,85,8,0,NaN,NaN,0,0,0,0,31,85,233,58700,0,3,6,1134607,4,Q1V22200011102,Q1V2220001110201

In [108]:
# Creating unique IDs for merging

#HHRV - Household ID
df_hhrv["hhid"] = df_hhrv['hhvar3'] + df_hhrv['hhvar4'] + df_hhrv['hhvar5'] + df_hhrv['hhvar13']+ df_hhrv['hhvar14']+ df_hhrv['hhvar15']+ df_hhrv['hhvar16']

##PERRV - Household ID
df_perrv["hhid"] = df_perrv['pvar3'] + df_perrv['pvar4'] + df_perrv['pvar5'] + df_perrv['pvar13'] + df_perrv['pvar14'] + df_perrv['pvar15'] + df_perrv['pvar16']

##PERRV - Person ID
df_perrv["perid"] = df_perrv['pvar3'] + df_perrv['pvar4'] + df_perrv['pvar5'] + df_perrv['pvar13'] + df_perrv['pvar14'] + df_perrv['pvar15'] + df_perrv['pvar16'] + df_perrv['pvar17']

In [109]:
#Merging HHV1 and PERV1
df_merged = pd.merge(df_hhrv,df_perrv, on = "hhid", how="outer",indicator= True)
df_merged["_merge"].value_counts() #Checking for unmerged rows

_merge
both          504440
left_only          0
right_only         0
Name: count, dtype: int64

In [119]:
df_merged.head()

,hhvar1,hhvar2,hhvar3,hhvar4,hhvar5,hhvar6,hhvar7,hhvar8,hhvar9,hhvar10,hhvar11,hhvar12,hhvar13,hhvar14,hhvar15,hhvar16,hhvar17,hhvar18,hhvar19,hhvar20,hhvar21,hhvar22,hhvar23,hhvar24,hhvar25,hhvar31,hhvar32,hhvar33,hhvar34,hhvar35,hhvar36,hhvar37,hhid,pvar1,pvar2,pvar3,pvar4,pvar5,pvar6,pvar7,pvar8,pvar9,pvar10,pvar11,pvar12,pvar13,pvar14,pvar15,pvar16,pvar17,pvar19,pvar20,pvar21,pvar22,pvar23,pvar24,pvar25,pvar26,pvar61,pvar62,pvar63,pvar64,pvar65,pvar66,pvar67,pvar68,pvar69,pvar70,pvar71,pvar72,pvar73,pvar74,pvar75,pvar76,pvar77,pvar78,pvar79,pvar80,pvar81,pvar82,pvar83,pvar84,pvar85,pvar86,pvar87,pvar88,pvar89,pvar90,pvar91,pvar92,pvar93,pvar94,pvar95,pvar96,pvar97,pvar98,pvar99,pvar100,pvar101,pvar102,pvar103,pvar104,pvar105,pvar106,pvar107,pvar108,pvar109,pvar110,pvar111,pvar112,pvar113,pvar114,pvar115,pvar116,pvar117,pvar118,pvar119,pvar120,pvar121,pvar122,pvar123,pvar124,pvar125,pvar126,pvar127,pvar128,pvar129,pvar130,pvar131,pvar132,pvar133,pvar134,pvar135,pvar136,pvar137,pvar138,pvar139,perid,_merge
0,RVH7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,07,1,1,NaN,4,2,1,3,17100,01,09072023,10,3,6,1134607,4,Q1V22200011101,RVP7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,01,1,1,45,2,08,01,10,NaN,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,8,0,NaN,NaN,0,0,8,0,31,25,721,20000,0,3,6,1134607,4,Q1V2220001110101,both
1,RVH7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,07,1,1,NaN,4,2,1,3,17100,01,09072023,10,3,6,1134607,4,Q1V22200011101,RVP7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,02,2,2,41,2,08,01,10,NaN,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,0,0,NaN,NaN,0,0,0,0,92,NaN,NaN,0,0,3,6,1134607,4,Q1V2220001110102,both
2,RVH7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,07,1,1,NaN,4,2,1,3,17100,01,09072023,10,3,6,1134607,4,Q1V22200011101,RVP7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,03,5,1,18,1,10,01,12,29,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,NaN,0,0,3,6,1134607,4,Q1V2220001110103,both
3,RVH7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,07,1,1,NaN,4,2,1,3,17100,01,09072023,10,3,6,1134607,4,Q1V22200011101,RVP7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,01,04,5,2,16,1,08,01,10,27,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,0,0,NaN,NaN,0,0,0,0,91,NaN,NaN,0,0,3,6,1134607,4,Q1V2220001110104,both
4,RVH7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,02,07,1,1,NaN,4,2,1,9,16475,01,09072023,11,3,6,1134607,4,Q1V22200011102,RVP7,104,Q1,V2,2,28,03,281,04,04,2,2822,20001,1,1,02,01,1,1,44,2,13,06,17,NaN,31,85,8,0,NaN,NaN,0,0,8,0,31,85,8,0,NaN,NaN,0,0,8,0,31,85,8,0,NaN,NaN,0,0,8,0,31,85,8,0,NaN,NaN,0,0,8,0,31,85,8,0,NaN,NaN,0,0,8,0,31,85,8,0,NaN,NaN,0,0,8,0,72,85,8,0,NaN,NaN,0,0,0,0,31,85,233,58700,0,3,6,1134607,4,Q1V2220001110201,both

# Exporting file in dta format

In [123]:
df_merged['hhvar20'] = df_merged['hhvar20'].astype(str)
df_merged.to_stata(r"..\Extracted_files\HHRV_PERRV_merged.dta", write_index=False)